"""Deterministic demo-data seeding: one clinician account plus a synthetic
patient cohort spanning CN -> MCI -> AD, generated by running real
synthetic MRI scans through the actual preprocessing/volumetry/FIS
pipeline (not hand-typed numbers) — the same code path the API exercises
for a real upload, exactly like the frontend's `mock-data.ts` cohort but
produced by the backend's own pipeline instead of a client-side formula.

Idempotent: re-running against an already-seeded database is a no-op.
"""

import datetime
import random

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.core.security import hash_password
from app.models.enums import DataSource, Sex
from app.repositories import patient_repo, user_repo
from app.services import scan_service

logger = get_logger(__name__)

DEMO_CLINICIAN_EMAIL = "clinician@fade.demo"
DEMO_CLINICIAN_PASSWORD = "fade-demo-2026"  # noqa: S105 - seed-only demo credential, not a real secret
COHORT_SIZE = 32
_SOURCES = [
    DataSource.OASIS,
    DataSource.OASIS,
    DataSource.OASIS,
    DataSource.ADNI,
    DataSource.CLINIC,
]


async def seed(db: AsyncSession) -> None:
    existing = await user_repo.get_by_email(db, DEMO_CLINICIAN_EMAIL)
    if existing is not None:
        logger.info("seed_skipped", reason="already seeded")
        return

    clinician = await user_repo.create(
        db,
        email=DEMO_CLINICIAN_EMAIL,
        hashed_password=hash_password(DEMO_CLINICIAN_PASSWORD),
        full_name="Demo Clinician",
    )
    await db.flush()

    rng = random.Random(20260818)
    base_date = datetime.date(2026, 1, 6)

    for i in range(COHORT_SIZE):
        severity = rng.random()
        age = round(58 + severity * 30 + rng.uniform(-5, 5))
        sex = Sex.F if rng.random() > 0.5 else Sex.M
        source = rng.choice(_SOURCES)
        scan_date = base_date + datetime.timedelta(days=rng.randint(0, 220))

        patient = await patient_repo.create(
            db, age=age, sex=sex, source=source, created_by_id=clinician.id
        )
        scan = await patient_repo.create_scan(
            db, patient_id=patient.id, scan_date=scan_date, file_path=None
        )
        await scan_service.process_synthetic_scan(db, scan, severity, seed=1000 + i)

        logger.info(
            "seed_patient_created",
            display_id=patient.display_id,
            severity=round(severity, 2),
            stage=scan.fis_result.stage.value if scan.fis_result else None,
        )

    await db.commit()
    logger.info("seed_complete", patients=COHORT_SIZE, clinician_email=DEMO_CLINICIAN_EMAIL)
