"""initial schema

Revision ID: d65864356d55
Revises: 
Create Date: 2026-08-18 10:10:01.135289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65864356d55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CLINICIAN', 'ADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('display_id', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('F', 'M', name='sex', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('OASIS', 'ADNI', 'CLINIC', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_display_id'), 'patients', ['display_id'], unique=True)
    op.create_table('scans',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREPROCESSING', 'EXTRACTING_BIOMARKERS', 'RUNNING_INFERENCE', 'COMPLETED', 'FAILED', name='scanstatus', native_enum=False, length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_patient_id'), 'scans', ['patient_id'], unique=False)
    op.create_table('biomarker_readings',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Enum('HIPPOCAMPAL_VOLUME', 'VENTRICLE_BRAIN_RATIO', 'CORTICAL_THICKNESS', name='biomarkerkey', native_enum=False, length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('abnormality', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomarker_readings_scan_id'), 'biomarker_readings', ['scan_id'], unique=False)
    op.create_table('fis_results',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('CN', 'MCI', 'AD', name='stage', native_enum=False, length=5), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('membership', sa.JSON(), nullable=False),
    sa.Column('fired_rules', sa.JSON(), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fis_results_scan_id'), 'fis_results', ['scan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fis_results_scan_id'), table_name='fis_results')
    op.drop_table('fis_results')
    op.drop_index(op.f('ix_biomarker_readings_scan_id'), table_name='biomarker_readings')
    op.drop_table('biomarker_readings')
    op.drop_index(op.f('ix_scans_patient_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_patients_display_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
